### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by vmeretin** [themobilecoder/headset_connection_event#2]
https://dart.dev/null-safety/migration-guide

**Comment by lxl518000** [comment]
pub get support please

**Comment by vmeretin** [comment]
@themobilecoder

**Comment by dan-gandolfo** [comment]
Hi every one,

Do you know if the master is ready for publication?

Thanks for your answer.

**Comment by rafdls** [comment]
Sorry everyone.

I've just published the latest one with null support. (2.0.0)

Thanks @vmeretin for the pull request!
